### ISSUE TITLE
8888端口未启动

### ISSUE THREAD

**Issue by laiquziru** [the-soloist/pwn-env-docker#1]
<img width="734" alt="image" src="https://github.com/the-soloist/pwn-env-docker/assets/31889178/4a326bc3-a57a-4258-859b-5117822ea9c3">

**Comment by the-soloist** [comment]
配置写错了，已修复

**Comment by laiquziru** [comment]
还是不行啊

**Comment by the-soloist** [comment]
是不是换镜像源了，镜像同步不是实时的。
急的话建议本地build。

**Comment by laiquziru** [comment]
没有啊   直接从新git  从新拉去镜像的

**Comment by laiquziru** [comment]
阿里云2核4G服务器上搭建的环境

**Comment by laiquziru** [comment]
![image](https://github.com/the-soloist/pwn-env-docker/assets/31889178/1a14041a-4246-4034-94c5-a1992fb9085e)
能正常进去

**Comment by the-soloist** [comment]
<img width="1025" alt="image" src="https://github.com/the-soloist/pwn-env-docker/assets/46804083/65dfb61e-f6fd-4723-9f30-917458cc5f20">

我这测试可以，建议换个镜像，或本地构建

（或者删掉原来的）

**Comment by laiquziru** [comment]
现在都好了  谢谢
